"""LLM-assisted source sentence context selection."""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any, cast

import base
import normative_audit


class SentenceContextSelection(base.FrozenModel):
    """Selected context IDs and materialized original text for one task."""

    task_id: str
    selected_context_sentence_ids: tuple[str, ...]
    original: str


class InvalidContextSelection(base.FrozenModel):
    """A context sentence ID selected by Codex but not available for the task."""

    task_id: str
    sentence_id: str
    reason: str


class SelectionRetryAttempt(base.FrozenModel):
    """One failed Codex selection attempt that triggered a retry."""

    attempt: int
    task_ids: tuple[str, ...]
    reason: str
    details: tuple[str, ...] = ()


class SentenceContextSelectionReport(base.FrozenModel):
    """LLM sentence context selection report."""

    selections: tuple[SentenceContextSelection, ...]
    conflicts: tuple[normative_audit.ContextSelectionConflict, ...]
    invalid_context_selections: tuple[InvalidContextSelection, ...] = ()
    retry_attempts: tuple[SelectionRetryAttempt, ...] = ()


class CodexContextSelectionError(RuntimeError):
    """`codex exec` failed while selecting source sentence contexts."""

    def __init__(self, *, command: tuple[str, ...], returncode: int, stdout: str, stderr: str) -> None:
        message = f"codex exec failed with returncode={returncode}"
        if stderr.strip():
            message = f"{message}\n\nstderr:\n{stderr.strip()}"
        if stdout.strip():
            message = f"{message}\n\nstdout:\n{stdout.strip()}"
        super().__init__(message)
        self.command = command
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


class SentenceContextSelectionRetryError(RuntimeError):
    """Codex kept returning invalid sentence context selections."""

    def __init__(self, *, attempts: tuple[SelectionRetryAttempt, ...]) -> None:
        latest = attempts[-1]
        super().__init__(
            "sentence context selection failed after retries: "
            f"attempt={latest.attempt} reason={latest.reason} task_ids={', '.join(latest.task_ids)}",
        )
        self.attempts = attempts


def load_sentence_selection_tasks(path: Path) -> tuple[normative_audit.SentenceSelectionTask, ...]:
    """Load sentence selection tasks generated by `sentence-selection-tasks`."""
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise TypeError("Sentence selection task file must contain a JSON object.")
    tasks = document["tasks"]
    if not isinstance(tasks, list):
        raise TypeError("Sentence selection task file must contain a tasks array.")
    return tuple(_sentence_selection_task_from_json(task) for task in tasks)


def select_sentence_contexts_with_codex(
    tasks: tuple[normative_audit.SentenceSelectionTask, ...],
    *,
    codex_command: str = "codex",
    model: str | None = None,
    timeout_seconds: int = 1800,
    stream_output: bool = False,
    max_retries: int = 3,
) -> SentenceContextSelectionReport:
    """Run Codex once to select context sentence IDs and validate the result."""
    tasks_by_id = {task.id: task for task in tasks}
    selected_ids_by_task_id: dict[str, tuple[str, ...]] = {}
    retry_attempts: list[SelectionRetryAttempt] = []
    pending_tasks = tasks
    retry_feedback: tuple[SelectionRetryAttempt, ...] = ()
    invalid_context_selections: tuple[InvalidContextSelection, ...] = ()
    conflicts: tuple[normative_audit.ContextSelectionConflict, ...] = ()

    for attempt in range(1, max_retries + 2):
        response = run_codex_context_selection(
            build_context_selection_prompt(pending_tasks, retry_feedback=retry_feedback),
            codex_command=codex_command,
            model=model,
            timeout_seconds=timeout_seconds,
            stream_output=stream_output,
        )
        attempt_selected_ids, missing_task_ids, extra_task_ids = _parse_selection_response(response, pending_tasks)
        selected_ids_by_task_id.update(attempt_selected_ids)
        sanitized_ids_by_task_id, invalid_context_selections = _sanitize_selected_context_ids(
            tuple(tasks_by_id[task_id] for task_id in selected_ids_by_task_id),
            selected_ids_by_task_id,
        )
        selected_ids_by_task_id = sanitized_ids_by_task_id
        conflicts = normative_audit.find_context_selection_conflicts(
            tuple(tasks_by_id[task_id] for task_id in selected_ids_by_task_id),
            selected_ids_by_task_id,
        )
        retry_feedback = _retry_attempts_for_validation(
            attempt=attempt,
            missing_task_ids=missing_task_ids,
            extra_task_ids=extra_task_ids,
            invalid_context_selections=invalid_context_selections,
            conflicts=conflicts,
        )
        if not retry_feedback and len(selected_ids_by_task_id) == len(tasks):
            break
        retry_attempts.extend(retry_feedback)
        retry_task_ids = _retry_task_ids(retry_feedback)
        for task_id in retry_task_ids:
            selected_ids_by_task_id.pop(task_id, None)
        if attempt > max_retries:
            raise SentenceContextSelectionRetryError(attempts=tuple(retry_attempts))
        pending_tasks = tuple(tasks_by_id[task_id] for task_id in retry_task_ids if task_id in tasks_by_id)
        if not pending_tasks:
            raise SentenceContextSelectionRetryError(attempts=tuple(retry_attempts))

    selections = tuple(
        SentenceContextSelection(
            task_id=task.id,
            selected_context_sentence_ids=selected_ids_by_task_id[task.id],
            original=normative_audit.build_selected_original(task, selected_ids_by_task_id[task.id]),
        )
        for task in tasks
    )
    return SentenceContextSelectionReport(
        selections=selections,
        conflicts=conflicts,
        invalid_context_selections=invalid_context_selections,
        retry_attempts=tuple(retry_attempts),
    )


def run_codex_context_selection(
    prompt: str,
    *,
    codex_command: str = "codex",
    model: str | None = None,
    timeout_seconds: int = 1800,
    stream_output: bool = False,
) -> str:
    """Invoke `codex exec` one-shot and return its final message."""
    with tempfile.TemporaryDirectory() as directory:
        temp_dir = Path(directory)
        output_path = temp_dir / "codex_last_message.txt"
        schema_path = temp_dir / "sentence_context_selection.schema.json"
        schema_path.write_text(json.dumps(_CODEX_OUTPUT_SCHEMA, indent=2) + "\n", encoding="utf-8")
        command = [
            codex_command,
            "exec",
            "--sandbox",
            "read-only",
            "--output-schema",
            str(schema_path),
            "--output-last-message",
            str(output_path),
        ]
        if model is not None:
            command.extend(("--model", model))
        command.append("-")
        if stream_output:
            completed = subprocess.run(
                command,
                input=prompt,
                stdout=None,
                stderr=None,
                text=True,
                check=False,
                timeout=timeout_seconds,
            )
        else:
            completed = subprocess.run(
                command,
                input=prompt,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout_seconds,
            )
        if completed.returncode != 0:
            raise CodexContextSelectionError(
                command=tuple(command),
                returncode=completed.returncode,
                stdout=completed.stdout or "",
                stderr=completed.stderr or "",
            )
        if output_path.exists():
            return output_path.read_text(encoding="utf-8")
        return completed.stdout


def build_context_selection_prompt(
    tasks: tuple[normative_audit.SentenceSelectionTask, ...],
    *,
    retry_feedback: tuple[SelectionRetryAttempt, ...] = (),
) -> str:
    """Build a JSON-only context selection prompt."""
    task_payload = [
        {
            "task_id": task.id,
            "block_id": task.block_id,
            "section": task.section,
            "block_original": task.block_original,
            "main_sentence": task.main_sentence.model_dump(mode="json"),
            "shared_context_sentences": [
                sentence.model_dump(mode="json") for sentence in task.shared_context_sentences
            ],
            "context_sentences": [sentence.model_dump(mode="json") for sentence in task.context_sentences],
        }
        for task in tasks
    ]
    retry_text = ""
    if retry_feedback:
        retry_payload = [attempt.model_dump(mode="json") for attempt in retry_feedback]
        retry_text = (
            "\nPrevious answer was invalid. Fix only the listed tasks and obey the validation feedback:\n"
            f"{json.dumps(retry_payload, ensure_ascii=False, indent=2)}\n"
        )
    return (
        "You are Codex. For each task, select the source sentence IDs that are needed as context for the "
        "main sentence.\n"
        "Select only IDs from shared_context_sentences or context_sentences.\n"
        "Sentence IDs are local to each task. Do not select an ID unless it is listed in that exact task.\n"
        "Do not rewrite source text. Do not add explanations.\n"
        "Return JSON only with this schema:\n"
        '{"selections":[{"task_id":"...","selected_context_sentence_ids":["s1","s3"]}]}\n\n'
        f"{retry_text}"
        f"Tasks:\n{json.dumps({'tasks': task_payload}, ensure_ascii=False, indent=2)}"
    )


def save_context_selection_report(report: SentenceContextSelectionReport, output_path: Path) -> None:
    """Save context selection report as JSON."""
    output_path.write_text(
        json.dumps(report.model_dump(mode="json"), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _parse_selection_response(
    response: str,
    tasks: tuple[normative_audit.SentenceSelectionTask, ...],
) -> tuple[dict[str, tuple[str, ...]], tuple[str, ...], tuple[str, ...]]:
    document = json.loads(_extract_json_object(response))
    raw_selections = document["selections"]
    selected_ids_by_task_id: dict[str, tuple[str, ...]] = {}
    for item in raw_selections:
        task_id = str(item["task_id"])
        selected_ids_by_task_id[task_id] = tuple(
            str(sentence_id) for sentence_id in item["selected_context_sentence_ids"]
        )

    expected_task_ids = {task.id for task in tasks}
    missing_task_ids = tuple(task_id for task_id in expected_task_ids if task_id not in selected_ids_by_task_id)
    extra_task_ids = tuple(task_id for task_id in selected_ids_by_task_id if task_id not in expected_task_ids)
    selected_ids_by_task_id = {
        task_id: ids for task_id, ids in selected_ids_by_task_id.items() if task_id in expected_task_ids
    }
    return selected_ids_by_task_id, missing_task_ids, extra_task_ids


def _retry_attempts_for_validation(
    *,
    attempt: int,
    missing_task_ids: tuple[str, ...],
    extra_task_ids: tuple[str, ...],
    invalid_context_selections: tuple[InvalidContextSelection, ...],
    conflicts: tuple[normative_audit.ContextSelectionConflict, ...],
) -> tuple[SelectionRetryAttempt, ...]:
    retry_attempts: list[SelectionRetryAttempt] = []
    if missing_task_ids:
        retry_attempts.append(
            SelectionRetryAttempt(attempt=attempt, task_ids=missing_task_ids, reason="missing_task_selection"),
        )
    if extra_task_ids:
        retry_attempts.append(
            SelectionRetryAttempt(attempt=attempt, task_ids=(), reason="unknown_task_id", details=extra_task_ids),
        )
    retry_attempts.extend(
        SelectionRetryAttempt(
            attempt=attempt,
            task_ids=(invalid_selection.task_id,),
            reason=invalid_selection.reason,
            details=(invalid_selection.sentence_id,),
        )
        for invalid_selection in invalid_context_selections
    )
    retry_attempts.extend(
        SelectionRetryAttempt(
            attempt=attempt,
            task_ids=conflict.task_ids,
            reason="context_selection_conflict",
            details=(conflict.sentence_id,),
        )
        for conflict in conflicts
    )
    return tuple(retry_attempts)


def _retry_task_ids(retry_attempts: tuple[SelectionRetryAttempt, ...]) -> tuple[str, ...]:
    task_ids: list[str] = []
    for retry_attempt in retry_attempts:
        task_ids.extend(retry_attempt.task_ids)
    return tuple(dict.fromkeys(task_ids))


def _sanitize_selected_context_ids(
    tasks: tuple[normative_audit.SentenceSelectionTask, ...],
    selected_ids_by_task_id: dict[str, tuple[str, ...]],
) -> tuple[dict[str, tuple[str, ...]], tuple[InvalidContextSelection, ...]]:
    sanitized_ids_by_task_id: dict[str, tuple[str, ...]] = {}
    invalid_context_selections: list[InvalidContextSelection] = []
    for task in tasks:
        allowed_ids = {
            sentence.id
            for sentence in (
                *task.shared_context_sentences,
                *task.context_sentences,
            )
        }
        valid_ids: list[str] = []
        for sentence_id in selected_ids_by_task_id[task.id]:
            if sentence_id in allowed_ids:
                valid_ids.append(sentence_id)
                continue
            invalid_context_selections.append(
                InvalidContextSelection(
                    task_id=task.id,
                    sentence_id=sentence_id,
                    reason="unknown_context_sentence_id",
                ),
            )
        sanitized_ids_by_task_id[task.id] = tuple(dict.fromkeys(valid_ids))
    return sanitized_ids_by_task_id, tuple(invalid_context_selections)


def _sentence_selection_task_from_json(document: object) -> normative_audit.SentenceSelectionTask:
    if not isinstance(document, dict):
        raise TypeError("Sentence selection task document must be an object.")
    task_document = cast(dict[str, object], document)
    shared_context_sentences = _list_field(task_document, "shared_context_sentences")
    context_sentences = _list_field(task_document, "context_sentences")
    return normative_audit.SentenceSelectionTask(
        id=str(task_document["id"]),
        block_id=str(task_document["block_id"]),
        source_span=str(task_document["source_span"]),
        section=str(task_document["section"]),
        kind=normative_audit.CandidateKind(str(task_document["kind"])),
        block_original=str(task_document["block_original"]),
        main_sentence=_source_sentence_from_json(task_document["main_sentence"]),
        shared_context_sentences=tuple(_source_sentence_from_json(sentence) for sentence in shared_context_sentences),
        context_sentences=tuple(_source_sentence_from_json(sentence) for sentence in context_sentences),
    )


def _source_sentence_from_json(document: object) -> normative_audit.SourceSentence:
    if not isinstance(document, dict):
        raise TypeError("Source sentence document must be an object.")
    sentence_document = cast(dict[str, object], document)
    signal_tags = _list_field(sentence_document, "signal_tags")
    return normative_audit.SourceSentence(
        id=str(sentence_document["id"]),
        text=str(sentence_document["text"]),
        has_keyword=bool(sentence_document["has_keyword"]),
        signal_tags=tuple(normative_audit.SignalTag(str(tag)) for tag in signal_tags),
    )


def _list_field(document: dict[Any, Any], key: str) -> list[object]:
    value = document[key]
    if not isinstance(value, list):
        raise TypeError(f"{key} must be an array.")
    return value


def _extract_json_object(response: str) -> str:
    stripped = response.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```(?:json)?\s*", "", stripped)
        stripped = re.sub(r"\s*```$", "", stripped)
    if stripped.startswith("{"):
        return stripped
    start = stripped.find("{")
    end = stripped.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError("LLM response did not contain a JSON object.")
    return stripped[start : end + 1]


_CODEX_OUTPUT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["selections"],
    "properties": {
        "selections": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["task_id", "selected_context_sentence_ids"],
                "properties": {
                    "task_id": {"type": "string"},
                    "selected_context_sentence_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
            },
        },
    },
}
